### ISSUE TITLE
Marker position on the OSIM model

### ISSUE THREAD

**Issue by claudia-lat** [claudia-lat/MAPest#2]
Comparing an old OSIM model of @MartaLorenzini with the new one generated with the code [here](https://github.com/MartaLorenzini/AnthropometricModel/blob/master/23Links_Model/FindParam.m) I noticed an offset on the markers position.
![no spherical](https://cloud.githubusercontent.com/assets/10923418/18013290/adbaf00e-6bbd-11e6-9385-58df16e320aa.jpg)

**Comment by claudia-lat** [comment]
By modifying the leftFoot joint from fixed to free-floating and considering spherical joints (except the leftFoot one), it seems that the matching between OSIM model and marker positions has improved.
![spheric](https://cloud.githubusercontent.com/assets/10923418/18013738/c337d9cc-6bbf-11e6-8fc5-11d2bf1e75f5.jpg)

**Comment by claudia-lat** [comment]
By re-writing the OSIM model with:
- pelvis link as floating base;
- spherical joints (BallJoints)

the offset between trajectory-markers and model-markers seems substantially decreased.

**Comment by francesco-romano** [comment]
@claudia-lat  can we close this issue?
