### ISSUE TITLE
Fix errors when using subject05 urdfs

### ISSUE THREAD

**Issue by fjandrad** [claudia-lat/MAPest#32]
**On branch: [floatingWithIWear](https://github.com/claudia-lat/MAPest/tree/floatingWithIWear)**

When using the 66dof model I get:
![image](https://user-images.githubusercontent.com/11043189/58641120-dea06800-82fa-11e9-8d7a-5b32e38a0b0e.png)

When using the 48dof model I get:
![image](https://user-images.githubusercontent.com/11043189/58641203-0bed1600-82fb-11e9-84c5-c37e45ab54c0.png)

I obtained the urdfs by coping the files from [here](https://github.com/robotology-playground/human-gazebo/tree/master/humanSubject05)

**Comment by fjandrad** [comment]
cc @claudia-lat sorry still having issues

**Comment by claudia-lat** [comment]
@fjandrad may we close this issue? Please write few lines on how you solved the problem.

**Comment by fjandrad** [comment]
The error was that the data was logged with the 66 dof so that explains the issue with the 48dof urdf. For the 66 dof the problem was it could not find the urdf at all so its not an error parsing but an error loading the file. In fact it was returning id -1 in the file name. We could add a check specifically on that. Looking at the exact path used I was able to correct the names and location of the files and put them there. That was enough.
