### ISSUE TITLE
Can we remove iDynTreeID.m ?

### ISSUE THREAD

**Issue by traversaro** [claudia-lat/MAPest#34]
The `iDynTreeID` functions uses the deprecated `iDynTree.DynamicsComputations`, that has been deprecated in favor of `iDynTree.KinDynComputations` . To avoid problems in the future, we can either migrate  `iDynTreeID` to use  `iDynTree.KinDynComputations`, or just remove it if it is not used anymore.

**Comment by traversaro** [comment]
@claudia-lat

**Comment by claudia-lat** [comment]
Yes @traversaro . Actually I just discovered that this function has been inherited from an old implementation of MAPest and actually is not used.  I'll take care to remove it from the repo.

**Comment by claudia-lat** [comment]
Done @traversaro. Thank you.
Closing.
