### ISSUE TITLE
Read robot positions

### ISSUE THREAD

**Issue by traversaro** [claudia-lat/MAPest#9]
To correctly map robot external wrenches to human external wrenches, we need to pass the robot joint positions for each instant to the [`processRobotWrenches`](https://github.com/claudia-lat/MAPest/blob/synchroSensors/Experiments/23links_human/src/processRobotWrenches.m) function. The joint positions can be extracted from the log of the `stateExt:o` ports. 
To see how to extract the joint positions from the logs, you can copy some logic from the `readStateExt` in @fjandrad's repository : 

https://github.com/robotology-playground/insitu-ft-analysis/blob/87f7f2315bcc2fedbe54f38e21e781ac39ffd914/utils/readStateExt.m

And by looking how this function is used: 

https://github.com/robotology-playground/insitu-ft-analysis/search?utf8=%E2%9C%93&q=readStateExt

.

**Comment by traversaro** [comment]
cc @MartaLorenzini

**Comment by traversaro** [comment]
cc @claudia-lat

**Comment by traversaro** [comment]
The ordering for the joints that we tipically use in the robot if the one that we use in `yarp-wholebodyinterface`: 
https://github.com/robotology/yarp-wholebodyinterface/blob/master/app/robots/iCubGenova02/yarpWholeBodyInterface.ini

In particular it is:

```
consideredJoints = iDynTree.StringVector();     
consideredJoints.push_back('torso_pitch');     
consideredJoints.push_back('torso_roll');     
consideredJoints.push_back('torso_yaw');    
consideredJoints.push_back('l_shoulder_pitch');  
consideredJoints.push_back('l_shoulder_roll');     
consideredJoints.push_back('l_shoulder_yaw');     
consideredJoints.push_back('l_elbow');    
consideredJoints.push_back('r_shoulder_pitch');     
consideredJoints.push_back('r_shoulder_roll');     
consideredJoints.push_back('r_shoulder_yaw');     
consideredJoints.push_back('r_elbow');     
consideredJoints.push_back('l_hip_pitch');     
consideredJoints.push_back('l_hip_roll');     
consideredJoints.push_back('l_hip_yaw');    
consideredJoints.push_back('l_knee');     
consideredJoints.push_back('l_ankle_pitch');     
consideredJoints.push_back('l_ankle_roll');     
consideredJoints.push_back('r_hip_pitch');     
consideredJoints.push_back('r_hip_roll');     
consideredJoints.push_back('r_hip_yaw');     
consideredJoints.push_back('r_knee');     
consideredJoints.push_back('r_ankle_pitch');     
consideredJoints.push_back('r_ankle_roll');
```

The order of each part is given in http://wiki.icub.org/wiki/ICub_joints .

**Comment by claudia-lat** [comment]
Robot positions correctly read by the algorithm.
Thanks @traversaro .
